#!/usr/bin/env bash

# Script to list the .yaml test files that failed in a `go test` run.
#
# Generated by Claude AI

if [ $# -eq 0 ]; then
    echo "Usage: $0 <logfile>"
    exit 1
fi

logfile="$1"

if [ ! -f "$logfile" ]; then
    echo "Error: File '$logfile' not found"
    exit 1
fi

# Each failing subtest is reported by `go test` on a line like:
#   --- FAIL: TestSPQ/ztests/sqlite/select2/ztests-1/q483.yaml/483 (0.01s)
# Extract the unique .yaml paths from those lines.
readarray -t failures < <(
    grep -- '--- FAIL:' "$logfile" \
        | grep -oE 'ztests/[^[:space:]]+\.yaml' \
        | sort -u
)

echo "=== TEST FAILURE SUMMARY ==="
echo ""
echo "Failed test files (${#failures[@]}):"
echo "============================"
for yaml in "${failures[@]}"; do
    echo "  $yaml"
done
