#!/usr/bin/env bash

# Script to summarize test failures by .yaml path and runtime type (vector/sequence)
#
# Generated by Claude AI

if [ $# -eq 0 ]; then
    echo "Usage: $0 <logfile>"
    exit 1
fi

logfile="$1"

if [ ! -f "$logfile" ]; then
    echo "Error: File '$logfile' not found"
    exit 1
fi

# Create associative arrays to track which runtimes failed for each yaml file
declare -A vector_failures
declare -A sequence_failures

# Read the log file and extract yaml paths with their runtime markers
current_yaml=""

while IFS= read -r line; do
    # Check if line contains a .yaml path
    if [[ "$line" =~ (ztests/[^:]+\.yaml) ]]; then
        current_yaml="${BASH_REMATCH[1]}"
    fi
    
    # Check for runtime markers
    if [[ -n "$current_yaml" ]]; then
        if [[ "$line" =~ ===\ vector\ === ]]; then
            vector_failures["$current_yaml"]=1
        elif [[ "$line" =~ ===\ sequence\ === ]]; then
            sequence_failures["$current_yaml"]=1
        fi
    fi
done < "$logfile"

# Get all unique yaml files
declare -A all_yamls
for yaml in "${!vector_failures[@]}"; do
    all_yamls["$yaml"]=1
done
for yaml in "${!sequence_failures[@]}"; do
    all_yamls["$yaml"]=1
done

# Sort yaml files for consistent output
readarray -t sorted_yamls < <(printf '%s\n' "${!all_yamls[@]}" | sort)

# Categorize and display results
echo "=== TEST FAILURE SUMMARY ==="
echo ""

vector_only=()
sequence_only=()
both=()

for yaml in "${sorted_yamls[@]}"; do
    has_vector=${vector_failures[$yaml]:-0}
    has_sequence=${sequence_failures[$yaml]:-0}
    
    if [[ $has_vector -eq 1 && $has_sequence -eq 1 ]]; then
        both+=("$yaml")
    elif [[ $has_vector -eq 1 ]]; then
        vector_only+=("$yaml")
    elif [[ $has_sequence -eq 1 ]]; then
        sequence_only+=("$yaml")
    fi
done

echo "Failed in BOTH vector and sequence (${#both[@]} tests):"
echo "================================================"
for yaml in "${both[@]}"; do
    echo "  $yaml"
done

echo ""
echo "Failed in VECTOR only (${#vector_only[@]} tests):"
echo "=========================================="
for yaml in "${vector_only[@]}"; do
    echo "  $yaml"
done

echo ""
echo "Failed in SEQUENCE only (${#sequence_only[@]} tests):"
echo "============================================"
for yaml in "${sequence_only[@]}"; do
    echo "  $yaml"
done

echo ""
echo "=== TOTALS ==="
echo "Total unique test files with failures: ${#all_yamls[@]}"
echo "  - Both runtimes: ${#both[@]}"
echo "  - Vector only: ${#vector_only[@]}"
echo "  - Sequence only: ${#sequence_only[@]}"
